# Generated by Django 5.1.2 on 2025-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
